apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: iep-employee
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: fund-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: fund-config
                  key: MONGO_PORT
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: fund-config
                  key: MONGO_DB_NAME
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: fund-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: fund-config
                  key: REDIS_PORT
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fund-secret
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fund-secret
                  key: MONGO_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fund-secret
                  key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: employee
spec:
  selector:
    app: employee
  ports:
    - port: 5001
      targetPort: 5001