apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
        - name: ganache
          image: trufflesuite/ganache-cli
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          ports:
            - containerPort: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: ganache
spec:
  type: LoadBalancer
  selector:
    app: ganache
  ports:
    - port: 8545
      targetPort: 8545