apiVersion: v1
kind: Secret
metadata:
  name: fund-secret
type: Opaque
stringData:
  MONGO_USERNAME: "root"
  MONGO_PASSWORD: "example"
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "example"
  JWT_SECRET_KEY: "super-secret-key-change-in-production"